WITH learning_period AS (
  SELECT DISTINCT
    ACTOR_EMAIL,
    IP_ADDRESS,
    EVENT_PARAMETERS:method_name method_name
  FROM RAW.GSUITE_ACTIVITY
  -- learning period, adjust per to your needs
  WHERE  ID_TIME BETWEEN '2023-07-01 00:00:00' AND '2023-09-01 00:00:00'
    AND ID_APPLICATION_NAME='token'
    AND EVENT_NAME='activity'
    AND IP_ADDRESS IS NOT NULL
)
  SELECT
     MIN(ID_TIME)   EARLIEST,
     MAX(ID_TIME)   LATEST,
    EVENT_PARAMETERS:client_id CLIENT_ID,
    EVENT_PARAMETERS:method_name METHOD_NAME,
    IFF(REGEXP_LIKE(EVENT_PARAMETERS:app_name, '[[:digit:]]+'), 'SA_TYPE', 'GWS_MARKETPLACE_APP') AS API_TYPE,
    ARRAY_AGG(DISTINCT IP_ADDRESS),
    ACTOR_EMAIL
  FROM RAW.GSUITE_ACTIVITY
    WHERE ID_APPLICATION_NAME='token'
    AND EVENT_NAME='activity'
    AND API_TYPE = 'SA_TYPE'
    AND  NOT (ACTOR_EMAIL, IP_ADDRESS, METHOD_NAME)  IN (SELECT ACTOR_EMAIL, IP_ADDRESS, METHOD_NAME FROM learning_period)
GROUP BY ACTOR_EMAIL,
         CLIENT_ID,
         METHOD_NAME,
         API_TYPE
